# Generated by Django 5.0.6 on 2024-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
